# NumPy Basics

In [1]:
import numpy as np

In [2]:
data1 = [2.0,5,5,6,7,8.0]

In [3]:
arr1 = np.array(data1)

In [4]:
arr1

array([2., 5., 5., 6., 7., 8.])

In [5]:
data2 = [[1,2,3],[4,5,6],[3,54,21]]

In [6]:
arr2 = np.array(data2)

In [7]:
arr2

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 3, 54, 21]])

In [8]:
arr2.ndim

2

In [9]:
arr2.shape

(3, 3)

In [10]:
arr1.dtype

dtype('float64')

In [11]:
arr2.dtype

dtype('int64')

In [12]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [13]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [14]:
np.empty((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [15]:
np.arange(20)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [16]:
np.ones_like(arr1)

array([1., 1., 1., 1., 1., 1.])

In [17]:
arr1

array([2., 5., 5., 6., 7., 8.])

In [18]:
np.full((3,3),5)

array([[5, 5, 5],
       [5, 5, 5],
       [5, 5, 5]])

In [19]:
np.identity(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [20]:
arr1.dtype

dtype('float64')

In [21]:
arr1

array([2., 5., 5., 6., 7., 8.])

In [22]:
arr3 = np.full((3,3),6.6)

In [23]:
arr3

array([[6.6, 6.6, 6.6],
       [6.6, 6.6, 6.6],
       [6.6, 6.6, 6.6]])

In [24]:
arr3.dtype

dtype('float64')

In [25]:
arr3.astype(np.int64)

array([[6, 6, 6],
       [6, 6, 6],
       [6, 6, 6]])

In [26]:
numeric_string = np.array(["90","20.7","45.6"],dtype = np.string_)

In [27]:
numeric_string.dtype

dtype('S4')

In [28]:
numeric_string

array([b'90', b'20.7', b'45.6'], dtype='|S4')

In [29]:
numeric_string.astype(np.float64)

array([90. , 20.7, 45.6])

In [30]:
arr3

array([[6.6, 6.6, 6.6],
       [6.6, 6.6, 6.6],
       [6.6, 6.6, 6.6]])

In [31]:
arr3 * arr3

array([[43.56, 43.56, 43.56],
       [43.56, 43.56, 43.56],
       [43.56, 43.56, 43.56]])

In [32]:
arr3*arr3

array([[43.56, 43.56, 43.56],
       [43.56, 43.56, 43.56],
       [43.56, 43.56, 43.56]])

In [33]:
arr3**arr3

array([[256442.48376486, 256442.48376486, 256442.48376486],
       [256442.48376486, 256442.48376486, 256442.48376486],
       [256442.48376486, 256442.48376486, 256442.48376486]])

In [34]:
1/arr3

array([[0.15151515, 0.15151515, 0.15151515],
       [0.15151515, 0.15151515, 0.15151515],
       [0.15151515, 0.15151515, 0.15151515]])

In [35]:
arr2 = np.array([[0.1,0.1,10],[0.2,0.5,9],[4,5,0]])

In [36]:
arr2

array([[ 0.1,  0.1, 10. ],
       [ 0.2,  0.5,  9. ],
       [ 4. ,  5. ,  0. ]])

In [37]:
arr3 > arr2

array([[ True,  True, False],
       [ True,  True, False],
       [ True,  True,  True]])

### Unlike Python slicing in case of numpy arrays , "views" are created of the arrays and any changes to that view is rreflected in the original array , as numpy doesn't copy the array while slicing

In [38]:
data = np.array([1,2,3,4,5,6,7,8,9,10])

In [44]:
data[5:7] = [100,200]

In [46]:
arr = data[:]

In [47]:
arr = 0

In [48]:
data

array([  1,   2,   3,   4,   5, 100, 200,   8,   9,  10])

In [49]:
arr

0

In [53]:
arr = data[1:4]

In [57]:
arr[:] = 0


In [58]:
data

array([  1,   0,   0,   0,   5, 100, 200,   8,   9,  10])

In [61]:
random = np.random.randn(3,3)
random

array([[-1.15908823, -1.45480036, -1.5792245 ],
       [ 0.77012754, -0.83233752,  0.05286526],
       [-0.14396013,  0.30237318, -0.42869153]])

In [67]:
random[:,:2]

array([[-1.15908823, -1.45480036],
       [ 0.77012754, -0.83233752],
       [-0.14396013,  0.30237318]])

In [69]:
random[random>0]

array([0.77012754, 0.05286526, 0.30237318])

In [70]:
boolean = random > 0

In [71]:
boolean

array([[False, False, False],
       [ True, False,  True],
       [False,  True, False]])

In [96]:
random[(random > 0.2) & (random < 0.9)] = 0

In [97]:
(random % 2 == 0) | (random % 6 == 0)

array([[False, False, False],
       [ True, False, False],
       [False,  True, False]])

In [98]:
random

array([[-1.15908823, -1.45480036, -1.5792245 ],
       [ 0.        , -0.83233752,  0.05286526],
       [-0.14396013,  0.        , -0.42869153]])

In [101]:
arr = np.empty([8,4])
arr

array([[5.24431042e-310, 0.00000000e+000, 0.00000000e+000,
        0.00000000e+000],
       [6.95314361e-310, 5.02034658e+175, 2.17732512e-076,
        1.50343917e+161],
       [1.39426277e+165, 7.27137895e-043, 8.29846706e-067,
        5.50597874e-144],
       [3.59751658e+252, 1.46901661e+179, 8.37404147e+242,
        2.59027926e-144],
       [3.80985069e+180, 1.41760146e+195, 4.96212127e+180,
        1.94919988e-153],
       [2.57642210e-056, 5.70102720e-066, 9.76333337e+165,
        9.12858942e+169],
       [1.41528119e+161, 1.56602272e-076, 3.11551021e-033,
        9.72100111e-067],
       [9.35443847e-067, 1.14484251e+243, 2.59903827e-144,
        5.24157015e-310]])

In [103]:
for i in range(8):
    arr[i] = i

In [104]:
arr

array([[0., 0., 0., 0.],
       [1., 1., 1., 1.],
       [2., 2., 2., 2.],
       [3., 3., 3., 3.],
       [4., 4., 4., 4.],
       [5., 5., 5., 5.],
       [6., 6., 6., 6.],
       [7., 7., 7., 7.]])

In [111]:
arr[[1,2,3,4]]
arr

array([[0., 0., 0., 0.],
       [1., 1., 1., 1.],
       [2., 2., 2., 2.],
       [3., 3., 3., 3.],
       [4., 4., 4., 4.],
       [5., 5., 5., 5.],
       [6., 6., 6., 6.],
       [7., 7., 7., 7.]])

In [110]:
arr[[0,1,2,5],[0,1,2,2]]

array([0., 1., 2., 5.])

In [112]:
arr

array([[0., 0., 0., 0.],
       [1., 1., 1., 1.],
       [2., 2., 2., 2.],
       [3., 3., 3., 3.],
       [4., 4., 4., 4.],
       [5., 5., 5., 5.],
       [6., 6., 6., 6.],
       [7., 7., 7., 7.]])

In [113]:
arr.T

array([[0., 1., 2., 3., 4., 5., 6., 7.],
       [0., 1., 2., 3., 4., 5., 6., 7.],
       [0., 1., 2., 3., 4., 5., 6., 7.],
       [0., 1., 2., 3., 4., 5., 6., 7.]])

In [114]:
np.dot(arr,arr.T)

array([[  0.,   0.,   0.,   0.,   0.,   0.,   0.,   0.],
       [  0.,   4.,   8.,  12.,  16.,  20.,  24.,  28.],
       [  0.,   8.,  16.,  24.,  32.,  40.,  48.,  56.],
       [  0.,  12.,  24.,  36.,  48.,  60.,  72.,  84.],
       [  0.,  16.,  32.,  48.,  64.,  80.,  96., 112.],
       [  0.,  20.,  40.,  60.,  80., 100., 120., 140.],
       [  0.,  24.,  48.,  72.,  96., 120., 144., 168.],
       [  0.,  28.,  56.,  84., 112., 140., 168., 196.]])

In [125]:
data2 = np.arange(16).reshape(2,2,4)
data2

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7]],

       [[ 8,  9, 10, 11],
        [12, 13, 14, 15]]])

In [126]:
data2.transpose((2,0,1))

array([[[ 0,  4],
        [ 8, 12]],

       [[ 1,  5],
        [ 9, 13]],

       [[ 2,  6],
        [10, 14]],

       [[ 3,  7],
        [11, 15]]])